In [2]:
import pandas as pd
import random as rd

In [3]:
df = pd.read_excel('data3.xlsx')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74368 entries, 0 to 74367
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 74368 non-null  int64
 1   record_id                  74368 non-null  int64
 2   athlete_id                 74368 non-null  int64
 3   event_name                 74368 non-null  object
 4   event_date                 74368 non-null  datetime64[ns]
 5   n_runners                  74368 non-null  int64
 6   finish_time                74368 non-null  int64
 7   position                   74368 non-null  int64
 8   athlete_gender             74368 non-null  object
 9   athlete_age                74368 non-null  int64
 10  best_time                  74368 non-null  int64
 11  worst_time                 74368 non-null  int64
 12  mean_time                  74368 non-null  float64
 13  median_time                74368 non-null  float64
 14  times                      74368 non-null  int64
 15  num_locations              74368 non-null  int64
 16  home                       74368 non-null  object
 17  temp                       74368 non-null  float64
 18  feels_like                 74368 non-null  float64
 19  pressure                   74368 non-null  int64
 20  humidity                   74368 non-null  int64
 21  dew_point                  74368 non-null  float64
 22  clouds                     74368 non-null  int64
 23  wind_speed                 74368 non-null  float64
 24  wind_deg                   74368 non-null  int64
 25  weather.main               74368 non-null  object
 26  weather.description        74368 non-null  object
 27  rain.1h                    7233 non-null   float64
 28  snow.1h                    3008 non-null   float64
 29  track_description_surface  74368 non-null  object
dtypes: datetime64[ns](1), float64(8), int64(15), object(6)
memory usage: 17.0+ MB

In [6]:
men_df = df[df['athlete_gender'] == 'мужской'] 
men_df

,Unnamed: 0,record_id,athlete_id,event_name,event_date,n_runners,finish_time,position,athlete_gender,athlete_age,...,humidity,dew_point,clouds,wind_speed,wind_deg,weather.main,weather.description,rain.1h,snow.1h,track_description_surface
0,22732,8002,790131949,Александрино,2023-05-27,24,1413,4,мужской,32,...,71,6.79,40,6.00,300,Clouds,scattered clouds,NaN,NaN,грунт
3,65895,8858,790130321,Александрино,2023-07-01,28,1520,8,мужской,48,...,56,13.68,0,4.02,270,Clear,clear sky,NaN,NaN,грунт
4,25323,8011,790131645,Александрино,2023-05-13,33,1520,7,мужской,33,...,55,6.06,0,4.02,320,Clear,clear sky,NaN,NaN,грунт
5,65848,8670,790130321,Александрино,2023-06-24,25,1462,2,мужской,48,...,78,17.86,20,3.13,300,Clouds,few clouds,NaN,NaN,грунт
6,65847,6803,790130321,Александрино,2023-04-08,89,1458,13,мужской,48,...,60,-2.73,0,2.00,110,Clear,clear sky,NaN,NaN,грунт
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74353,73010,10393,790125667,Якутск Дохсун,2023-09-02,36,1419,10,мужской,63,...,65,1.62,40,3.13,10,Clouds,scattered clouds,NaN,NaN,твердое
74354,73013,11775,790125667,Якутск Дохсун,2023-10-21,25,1433,7,мужской,63,...,85,-10.84,75,0.00,0,Snow,light shower snow,NaN,NaN,твердое
74356,73021,5773,790125667,Якутск Дохсун,2023-02-25,10,1473,5,мужской,63,...,73,-39.80,0,1.00,170,Mist,mist,NaN,NaN,твердое
74358,59045,10191,790149338,Якутск Дохсун,2023-08-26,28,2199,34,мужской,43,...,66,5.91,0,0.00,0,Clear,clear sky,NaN,NaN,твердое
74360,13234,10578,790150909,Якутск Дохсун,2023-09-09,31,1672,22,мужской,24,...,86,2.78,100,5.00,300,Rain,light intensity shower rain,NaN,NaN,твердое

In [7]:
women_df = df[df['athlete_gender'] == 'женский']
women_df

,Unnamed: 0,record_id,athlete_id,event_name,event_date,n_runners,finish_time,position,athlete_gender,athlete_age,...,humidity,dew_point,clouds,wind_speed,wind_deg,weather.main,weather.description,rain.1h,snow.1h,track_description_surface
1,43498,9401,790127832,Александрино,2023-07-22,25,1927,17,женский,38,...,72,12.81,40,8.05,260,Clouds,scattered clouds,NaN,NaN,грунт
2,65916,7495,790113063,Александрино,2023-05-06,28,1537,6,женский,48,...,42,-6.46,40,6.00,10,Clouds,scattered clouds,NaN,NaN,грунт
9,65924,7085,790113063,Александрино,2023-04-22,15,1549,6,женский,48,...,62,3.84,0,5.00,270,Clear,clear sky,NaN,NaN,грунт
14,43647,8858,790140534,Александрино,2023-07-01,28,1976,17,женский,38,...,56,13.68,0,4.02,270,Clear,clear sky,NaN,NaN,грунт
23,66299,6803,790130991,Александрино,2023-04-08,89,1839,61,женский,48,...,60,-2.73,0,2.00,110,Clear,clear sky,NaN,NaN,грунт
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74363,7685,10578,790150586,Якутск Дохсун,2023-09-09,31,2603,32,женский,15,...,86,2.78,100,5.00,300,Rain,light intensity shower rain,NaN,NaN,твердое
74364,7697,7326,790132030,Якутск Дохсун,2023-05-06,44,2663,56,женский,15,...,56,-1.26,0,2.00,140,Clear,clear sky,NaN,NaN,твердое
74365,7716,11377,790150586,Якутск Дохсун,2023-10-07,44,2803,51,женский,15,...,100,-1.06,100,3.13,160,Snow,heavy shower snow,NaN,0.39,твердое
74366,7626,10578,790134534,Якутск Дохсун,2023-09-09,31,2346,31,женский,15,...,86,2.78,100,5.00,300,Rain,light intensity shower rain,NaN,NaN,твердое
74367,36689,9966,790146613,Якутск Дохсун,2023-08-12,24,2268,26,женский,36,...,73,15.89,99,2.00,150,Smoke,smoke,NaN,NaN,твердое

In [10]:
topFast_men = men_df.groupby('event_name').agg({'finish_time': 'mean'}).reset_index()
topFast_men = topFast_men.sort_values(by='finish_time')
topFast_men.columns = ['event_name', 'city_mean_time'] 
topFast_cities_men = topFast_men.head(5)['event_name'].unique()
topFast_cities_men

array(['Йошкар-Ола Аллея Здоровья', 'Мега Парк Кудрово', 'Парк Кирова',
       'Чебоксары набережная', 'Пушкин'], dtype=object)

In [17]:
topSlow_men = men_df.groupby('event_name').agg({'finish_time': 'mean'}).reset_index()
topSlow_men = topSlow_men.sort_values(by='finish_time', ascending=[0])
topSlow_men.columns = ['event_name', 'city_mean_time'] 
topSlow_cities_men = topSlow_men.head(5)['event_name'].unique()
topSlow_cities_men

array(['Томск Сосновый Бор', 'Зеленогорск набережная',
       'Люберцы Томилинский', 'Стрелка', 'Петровская набережная'],
      dtype=object)

In [11]:
topFast_women = women_df.groupby('event_name').agg({'finish_time': 'mean'}).reset_index()
topFast_women = topFast_women.sort_values(by='finish_time')
topFast_women.columns = ['event_name', 'city_mean_time'] 
topFast_cities_women = topFast_women.head(5)['event_name'].unique()
topFast_cities_women

array(['Парк Кирова', 'Боева Дача', 'Городской парк Семья',
       'Йошкар-Ола Аллея Здоровья', 'Воркута Городской парк'],
      dtype=object)

In [19]:
topSlow_women = women_df.groupby('event_name').agg({'finish_time': 'mean'}).reset_index()
topSlow_women = topSlow_women.sort_values(by='finish_time', ascending=[0])
topSlow_women.columns = ['event_name', 'city_mean_time'] 
topSlow_cities_women = topSlow_women.head(5)['event_name'].unique()
topSlow_cities_women

array(['Томск Сосновый Бор', 'Стрежевой Городской парк',
       'Зеленогорск набережная', 'Петровская набережная',
       'Электросталь Авангард'], dtype=object)

In [12]:
dfFast_men = df[df['event_name'].isin(topFast_cities_men)]
dfFast_men = dfFast_men.sort_values(by='event_name')
dfFastFull_men = pd.merge(dfFast_men, topFast_men, on='event_name')
dfFastFull_men

,Unnamed: 0,record_id,athlete_id,event_name,event_date,n_runners,finish_time,position,athlete_gender,athlete_age,...,dew_point,clouds,wind_speed,wind_deg,weather.main,weather.description,rain.1h,snow.1h,track_description_surface,city_mean_time
0,69634,10034,790148524,Йошкар-Ола Аллея Здоровья,2023-08-19,30,1777,28,мужской,52,...,14.83,33,3.99,29,Clouds,scattered clouds,NaN,NaN,асфальт,1517.421927
1,53493,9398,790135167,Йошкар-Ола Аллея Здоровья,2023-07-22,33,1786,30,женский,41,...,13.51,14,3.55,255,Clouds,few clouds,NaN,NaN,асфальт,1517.421927
2,12484,13458,790159548,Йошкар-Ола Аллея Здоровья,2023-12-16,17,1585,6,мужской,23,...,-12.01,100,4.47,164,Snow,light snow,NaN,0.33,асфальт,1517.421927
3,29001,7381,790134475,Йошкар-Ола Аллея Здоровья,2023-05-06,19,1934,16,женский,34,...,4.59,100,2.85,327,Rain,light rain,0.54,NaN,асфальт,1517.421927
4,39217,12067,790156889,Йошкар-Ола Аллея Здоровья,2023-10-28,31,1766,21,женский,37,...,-4.83,100,3.58,129,Snow,light snow,NaN,0.32,асфальт,1517.421927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,12140,10753,790150070,Чебоксары набережная,2023-09-09,15,2124,15,женский,22,...,10.15,100,3.00,350,Mist,mist,NaN,NaN,твердое,1542.186047
1531,12144,11756,790150070,Чебоксары набережная,2023-10-14,11,2136,10,женский,22,...,2.62,0,12.07,220,Clear,clear sky,NaN,NaN,твердое,1542.186047
1532,12153,10805,790150070,Чебоксары набережная,2023-09-16,10,2172,8,женский,22,...,6.12,0,1.00,110,Clear,clear sky,NaN,NaN,твердое,1542.186047
1533,12163,11132,790150070,Чебоксары набережная,2023-09-23,16,2216,17,женский,22,...,14.91,0,3.00,190,Clear,clear sky,NaN,NaN,твердое,1542.186047
1534,55274,11967,790142578,Чебоксары набережная,2023-10-21,14,1521,7,женский,42,...,1.22,100,5.00,40,Clouds,overcast clouds,NaN,NaN,твердое,1542.186047

In [20]:
dfSlow_men = df[df['event_name'].isin(topSlow_cities_men)]
dfSlow_men = dfSlow_men.sort_values(by='event_name')
dfSlowFull_men = pd.merge(dfSlow_men, topSlow_men, on='event_name')
dfSlowFull_men

,Unnamed: 0,record_id,athlete_id,event_name,event_date,n_runners,finish_time,position,athlete_gender,athlete_age,...,dew_point,clouds,wind_speed,wind_deg,weather.main,weather.description,rain.1h,snow.1h,track_description_surface,city_mean_time
0,69360,11986,790156828,Зеленогорск набережная,2023-10-28,29,1406,5,женский,52,...,-8.77,90,6.54,258,Clouds,overcast clouds,NaN,NaN,твердое,2079.954545
1,73259,11986,790156421,Зеленогорск набережная,2023-10-28,29,1695,11,женский,64,...,-8.77,90,6.54,258,Clouds,overcast clouds,NaN,NaN,твердое,2079.954545
2,51087,12585,790156832,Зеленогорск набережная,2023-11-18,16,2060,5,женский,40,...,-1.88,96,2.09,243,Clouds,overcast clouds,NaN,NaN,твердое,2079.954545
3,7724,13710,790157316,Зеленогорск набережная,2023-12-30,9,2944,8,мужской,15,...,-2.19,100,4.08,215,Clouds,overcast clouds,NaN,NaN,твердое,2079.954545
4,38413,11986,790156477,Зеленогорск набережная,2023-10-28,29,1585,8,мужской,37,...,-8.77,90,6.54,258,Clouds,overcast clouds,NaN,NaN,твердое,2079.954545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,64737,9450,790142368,Томск Сосновый Бор,2023-07-29,11,1515,1,мужской,47,...,17.92,84,1.34,9,Clouds,broken clouds,NaN,NaN,смешанное,2278.065306
1864,57099,8925,790142432,Томск Сосновый Бор,2023-07-08,18,3537,17,женский,42,...,18.97,96,0.68,279,Clouds,overcast clouds,NaN,NaN,смешанное,2278.065306
1865,9030,12793,790159116,Томск Сосновый Бор,2023-11-25,45,1850,13,мужской,17,...,-1.44,100,3.87,124,Snow,light snow,NaN,0.38,смешанное,2278.065306
1866,56899,11600,790155286,Томск Сосновый Бор,2023-10-14,61,2461,42,женский,42,...,0.03,27,5.33,202,Clouds,scattered clouds,NaN,NaN,смешанное,2278.065306
1867,8543,11988,790123894,Томск Сосновый Бор,2023-10-28,54,3618,50,женский,16,...,-8.05,77,4.05,232,Clouds,broken clouds,NaN,NaN,смешанное,2278.065306

In [14]:
dfFast_women = df[df['event_name'].isin(topFast_cities_women)]
dfFast_women = dfFast_women.sort_values(by='event_name')
dfFastFull_women = pd.merge(dfFast_women, topFast_women, on='event_name')
dfFastFull_women

,Unnamed: 0,record_id,athlete_id,event_name,event_date,n_runners,finish_time,position,athlete_gender,athlete_age,...,dew_point,clouds,wind_speed,wind_deg,weather.main,weather.description,rain.1h,snow.1h,track_description_surface,city_mean_time
0,6055,11270,790138113,Боева Дача,2023-09-30,87,1587,58,мужской,14,...,8.49,0,1.00,0,Clear,clear sky,NaN,NaN,асфальт и тротуарная плитка,1750.835714
1,34464,11658,790152599,Боева Дача,2023-10-14,62,1608,40,мужской,36,...,5.08,0,4.02,160,Clear,clear sky,NaN,NaN,асфальт и тротуарная плитка,1750.835714
2,38629,13595,790136382,Боева Дача,2023-12-23,40,1639,26,мужской,37,...,-0.47,100,3.00,230,Clouds,overcast clouds,NaN,NaN,асфальт и тротуарная плитка,1750.835714
3,34723,11434,790152599,Боева Дача,2023-10-07,49,1669,37,мужской,36,...,-0.24,0,4.92,232,Clear,clear sky,NaN,NaN,асфальт и тротуарная плитка,1750.835714
4,34478,7736,790135453,Боева Дача,2023-05-20,63,1616,41,женский,36,...,8.01,0,7.15,60,Clear,clear sky,NaN,NaN,асфальт и тротуарная плитка,1750.835714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,73394,6553,790127435,Парк Кирова,2023-04-01,10,1563,4,мужской,65,...,2.06,100,0.89,157,Clouds,overcast clouds,NaN,NaN,твердое,1685.366667
1881,65185,7915,790133992,Парк Кирова,2023-05-27,16,1855,19,мужской,47,...,15.59,94,0.45,102,Clouds,overcast clouds,NaN,NaN,твердое,1685.366667
1882,73538,12991,790127435,Парк Кирова,2023-12-02,15,1685,8,мужской,66,...,-7.87,100,1.34,90,Snow,light snow,NaN,0.17,твердое,1685.366667
1883,73923,13724,790159904,Парк Кирова,2023-12-30,19,1871,14,мужской,69,...,-15.88,100,2.37,265,Clouds,overcast clouds,NaN,NaN,твердое,1685.366667
1884,16429,8373,790126972,Парк Кирова,2023-06-10,22,1125,1,мужской,28,...,12.24,78,1.34,354,Clouds,broken clouds,NaN,NaN,твердое,1685.366667

In [21]:
dfSlow_women = df[df['event_name'].isin(topSlow_cities_women)]
dfSlow_women = dfSlow_women.sort_values(by='event_name')
dfSlowFull_women = pd.merge(dfSlow_women, topSlow_women, on='event_name')
dfSlowFull_women

,Unnamed: 0,record_id,athlete_id,event_name,event_date,n_runners,finish_time,position,athlete_gender,athlete_age,...,dew_point,clouds,wind_speed,wind_deg,weather.main,weather.description,rain.1h,snow.1h,track_description_surface,city_mean_time
0,69360,11986,790156828,Зеленогорск набережная,2023-10-28,29,1406,5,женский,52,...,-8.77,90,6.54,258,Clouds,overcast clouds,NaN,NaN,твердое,2466.083333
1,73259,11986,790156421,Зеленогорск набережная,2023-10-28,29,1695,11,женский,64,...,-8.77,90,6.54,258,Clouds,overcast clouds,NaN,NaN,твердое,2466.083333
2,51087,12585,790156832,Зеленогорск набережная,2023-11-18,16,2060,5,женский,40,...,-1.88,96,2.09,243,Clouds,overcast clouds,NaN,NaN,твердое,2466.083333
3,7724,13710,790157316,Зеленогорск набережная,2023-12-30,9,2944,8,мужской,15,...,-2.19,100,4.08,215,Clouds,overcast clouds,NaN,NaN,твердое,2466.083333
4,38413,11986,790156477,Зеленогорск набережная,2023-10-28,29,1585,8,мужской,37,...,-8.77,90,6.54,258,Clouds,overcast clouds,NaN,NaN,твердое,2466.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1694,65059,13689,790141823,Электросталь Авангард,2023-12-23,68,1739,28,мужской,47,...,1.43,100,5.21,152,Snow,light snow,NaN,0.20,твердое,2432.666667
1695,22929,13689,790157815,Электросталь Авангард,2023-12-23,68,1511,11,мужской,32,...,1.43,100,5.21,152,Snow,light snow,NaN,0.20,твердое,2432.666667
1696,30931,15198,790160406,Электросталь Авангард,2023-12-30,17,1586,6,мужской,35,...,0.92,100,5.36,265,Snow,light snow,NaN,0.18,твердое,2432.666667
1697,40301,13689,790157186,Электросталь Авангард,2023-12-23,68,2092,52,мужской,37,...,1.43,100,5.21,152,Snow,light snow,NaN,0.20,твердое,2432.666667
1698,31916,13689,790160406,Электросталь Авангард,2023-12-23,68,1861,36,мужской,35,...,1.43,100,5.21,152,Snow,light snow,NaN,0.20,твердое,2432.666667

In [22]:
dfFastFull_men.to_excel('fast_men.xlsx')
dfSlowFull_men.to_excel('slow_men.xlsx')
dfFastFull_women.to_excel('fast_women.xlsx')
dfSlowFull_women.to_excel('slow_women.xlsx')